{{ config(alias="dim_plano_acao") }}

-- Dimensao do plano de acao de TED: atributos do plano e do programa, origem
-- do recurso e vigencia. vigente e calculado contra data_referencia, a data da
-- carga, exposta na propria dimensao.
select
    {{ surrogate_key(["p.id_plano_acao"]) }} as sk_plano_acao,
    p.id_plano_acao,
    p.num_transf,
    p.ano_instrumento,
    p.ano,
    p.situacao,
    p.objeto,
    p.justificativa,
    p.data_inicio_vigencia,
    p.data_fim_vigencia,
    current_date as data_referencia,
    coalesce(p.data_fim_vigencia >= current_date, false) as vigente,
    p.execucao_direta,
    p.execucao_particulares,
    p.execucao_descentralizada,
    p.sigla_unidade_descentralizada,
    p.unidade_descentralizada,
    p.sigla_unidade_responsavel_execucao,
    p.unidade_responsavel_execucao,
    p.id_programa,
    p.codigo_programa,
    p.nome_programa,
    p.ano_programa,
    p.situacao_programa,
    p.sigla_unidade_responsavel_acompanhamento,
    p.unidade_responsavel_acompanhamento,
    p.nome_institucional_programa,
    p.objetivo_programa,
    p.autoriza_subdescentralizacao,
    p.autoriza_realizacao_despesas,
    p.autoriza_execucao_creditos_descentralizada,
    p.origem_recurso,
    p.complemento_proprio
from {{ ref("ted_plano_acao") }} as p

union all

select
    -1::bigint,
    -1,
    null,
    null,
    null,
    'Não identificado',
    'Não identificado',
    null,
    null,
    null,
    current_date,
    false,
    null,
    null,
    null,
    null,
    'Não identificado',
    null,
    null,
    null,
    null,
    'Não identificado',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Não identificada',
    false
